export const START_LINKS_LOADING = 'START_LINKS_LOADING';
export const LINKS_LOADED = 'LINKS_LOADED';
export const CLEAR_LICKS = 'CLEAR_LICKS';
export const START_IMAGES_LOADING = 'START_LOADING';
export const IMAGES_LOADED = 'IMAGES_LOADED';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';