//login
export const START_LOGIN = 'START_LOGIN';
export const lOGIN = 'lOGIN';
export const LOAD_KEY = 'LOAD_KEY';


//LOAD LINK
export const START_LINKS_LOADING = 'START_LINKS_LOADING';
export const LINKS_LOADED = 'LINKS_LOADED';
export const CLEAR_LINKS = 'CLEAR_LINKS';
export const GET_ID_LINK = 'GET_ID_LINK';

///LOAD CHART
export const START_CHART_LOADING = 'START_CHART_LOADING';
export const CHART_LOADED = 'CHART_LOADED';
export const CLEAR_CHART = 'CLEAR_CHART';

///LOAD GROUP
export const START_GROUP_LOADING = 'START_GROUP_LOADING';
export const GROUP_LOADED = 'GROUP_LOADED';
export const CLEAR_GROUP = 'CLEAR_GROUP';
export const GET_ID_GROUP = 'GET_ID_GROUP';

///LOAD GROUP DETAIL
export const START_GROUPDETAIL_LOADING = 'START_GROUPDETAIL_LOADING';
export const GROUPDETAIL_LOADED = 'GROUPDETAIL_LOADED';
export const CLEAR_GROUPDETAIL = 'CLEAR_GROUPDETAIL';

export const SET_LINKS_GROUP = 'SET_LINKS_GROUP';
export const SET_USERS_GROUP = 'SET_USERS_GROUP';
export const SET_CAMPAIGNS_GROUP = 'SET_CAMPAIGNS_GROUP';

// LOAD CAMPAIGNS
export const START_CAMPAIGNS_LOADING = 'START_CAMPAIGNS_LOADING';
export const CAMPAIGNS_LOADED = 'CAMPAIGNS_LOADED';
export const CLEAR_CAMPAIGNS = 'CLEAR_CAMPAIGNS';
export const GET_ID_CAMPAIGNS = 'GET_ID_CAMPAIGNS';

//IMAGES_LOADED
export const START_IMAGES_LOADING = 'START_LOADING';
export const IMAGES_LOADED = 'IMAGES_LOADED';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';